---
- name: add the docker repository
  apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present
- name: update the apt cache
  apt: update_cache=yes
- name: install docker
  apt: name=lxc-docker state=latest
